<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{963367b4-7853-46d9-a119-421c43f5684c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//Main Terminal INPUTS
		//Part 1(Conveyor 1)	
	Inp_Part_at_Conveyor_1								AT%I*:BOOL;
	Inp_Plunger_Parts_Container_In						AT%I*:BOOL;
	Inp_Plunger_Parts_Container_Out						AT%I*:BOOL;
	Inp_Part_On_Conveyor_1								AT%I*:BOOL;
	Inp_Part_in_front_of_Parts_Alignment				AT%I*:BOOL;
	Inp_Plunger_Parts_Alignment_Left_In					AT%I*:BOOL;
	Inp_Plunger_Parts_Alignment_Left_Out				AT%I*:BOOL;
	Inp_Plunger_Parts_Alignment_Right_In				AT%I*:BOOL;	
	
	Inp_Plunger_Parts_Alignment_Right_Out				AT%I*:BOOL;
	Inp_Plunger_Parts_Alignment_Above_In				AT%I*:BOOL;
	Inp_Plunger_Parts_Alignment_Above_Out				AT%I*:BOOL;
	Inp_Part_in_front_of_Crane							AT%I*:BOOL;
	Inp_Crane_In										AT%I*:BOOL;
	Inp_Crane_Out										AT%I*:BOOL;
	Inp_Crane_Above										AT%I*:BOOL;
	Inp_Crane_Below										AT%I*:BOOL;
	
	Inp_Motor_1_Protection_Switch_is_OK					AT%I*:BOOL;
	
		//Part 2(Conveyor 2)	
	Inp_Conveyor_2_Palette_Left_Side					AT%I*:BOOL;
	Inp_Conveyor_2_Palette_Right_Side					AT%I*:BOOL;
	Inp_Palette_in_front_of_Tester						AT%I*:BOOL;
	Inp_Stopper_Below									AT%I*:BOOL;
	Inp_Stopper_Above									AT%I*:BOOL;
	Inp_Feedback_from_Tester							AT%I*:BOOL;
	Inp_Reserve_1										AT%I*:BOOL;
	Inp_Motor_2_Protection_Switch_is_OK					AT%I*:BOOL;
	
	Inp_Conveyor_2_Pallete_Slider_In					AT%I*:BOOL;
	Inp_Conveyor_2_Pallete_Slider_Out					AT%I*:BOOL;
		
		//Part 3(Conveyor 3)
	Inp_Conveyor_3_Palette_Left_Side					AT%I*:BOOL;
	Inp_Conveyor_3_Palette_Right_Side					AT%I*:BOOL;	
	Inp_Conveyor_3_Pallete_Slider_In					AT%I*:BOOL;
	Inp_Conveyor_3_Pallete_Slider_Out					AT%I*:BOOL;	
	Inp_Motor_3_Protection_Switch_is_OK					AT%I*:BOOL;

	//Coupler	
		//Part 4(Sorting System)
	Inp_Sortierer_in_Basik_Position						AT%I*:BOOL;
	Inp_Sortierer_Pluger_Above							AT%I*:BOOL;
	Inp_Sortierer_Pluger_Below							AT%I*:BOOL;
	Inp_Measuring_Bar_Sorting_Axis_X					AT%I*:INT;
	Inp_Measuring_Bar_Sorting_Axis_Y					AT%I*:INT;
	

	//Main Terminal OUTPUTS
		//Part 1(Conveyor 1)	
	Out_Conveyor_1_Motor_On								AT%Q*:BOOL;
	Out_Plunger_Parts_Container_Drive_In				AT%Q*:BOOL;
	Out_Plunger_Parts_Container_Drive_Out				AT%Q*:BOOL;
	Out_Plunger_Parts_Alignment_Left_Drive_In			AT%Q*:BOOL;
	Out_Plunger_Parts_Alignment_Left_Drive_Out			AT%Q*:BOOL;
	Out_Plunger_Parts_Alignment_Right_Drive_In			AT%Q*:BOOL;		
	Out_Plunger_Parts_Alignment_Right_Drive_Out			AT%Q*:BOOL;
	Out_Plunger_Parts_Alignment_Above_Drive_In			AT%Q*:BOOL;
	
	Out_Plunger_Parts_Alignment_Above_Drive_Out			AT%Q*:BOOL;
	Out_Crane_Drive_In									AT%Q*:BOOL;
	Out_Crane_Drive_Out									AT%Q*:BOOL;
	Out_Crane_Drive_Up									AT%Q*:BOOL;
	Out_Crane_Drive_Down								AT%Q*:BOOL;
	
		//Part 2(Conveyor 2)	
	Out_Conveyor_2_Motor_On								AT%Q*:BOOL;
	Out_Stopper_Drive_Up								AT%Q*:BOOL;
	Out_Stopper_Drive_Down								AT%Q*:BOOL;
	Out_Conveyor_2_Pallete_Slider_Drive_In				AT%Q*:BOOL;
	Out_Conveyor_2_Pallete_Slider_Drive_Out				AT%Q*:BOOL;
	
		//Part 3(Conveyor 3)
	Out_Conveyor_3_Motor_On								AT%Q*:BOOL;	
	Out_Conveyor_3_Pallete_Slider_Drive_In				AT%Q*:BOOL;
	Out_Conveyor_3_Pallete_Slider_Drive_Out				AT%Q*:BOOL;

	//Coupler	
		//Part 4(Sorting System)
	Out_Sortierer_Pluger_Drive_Up						AT%Q*:BOOL;
	Out_Sortierer_Pluger_Drive_Down						AT%Q*:BOOL;	
	Out_Measuring_Bar_Sorting_Axis_X_Motor_On			AT%Q*:BOOL;
	Out_Measuring_Bar_Sorting_Axis_Y_Motor_On			AT%Q*:BOOL;
	Out_Sortierer_Pluger_Pull_in						AT%Q*:BOOL;
	
	position:Positions;
	a:INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>