<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="INFO" Id="{7395f367-245f-4505-b18a-cedd56194bd6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INFO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Couter_R_TRIG(
CLK:= , 
Q=> );]]></ST>
    </Implementation>
    <LineIds Name="INFO">
      <LineId Id="9" Count="0" />
      <LineId Id="11" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>